### ISSUE TITLE
Add ffmpeg copy codec option to speed up download

### ISSUE THREAD

**Issue by kokorin** [BohdanAndrusiak/UaTgBotForFilms#1]
https://github.com/BohdanAndrusiak/UaTgBotForFilms/blob/1ba5361508a6aaaab1a2777a53bcc1ac0bb99ca9/src/main/java/com/bandrusiak/service/impl/DownloaderServiceImpl.java#L43

It should be 
```java
UrlOutput.toUrl(pathToVideoOnPc).copyAllCodecs()
```

**Comment by BohdanAndrusiak** [comment]
Wow, this is speed up download time in 12x (60min -> 5min on my PC for test file 1.6Gb). 
Thank you so much for help.
